ignoredBuiltDependencies:
  - bufferutil

packages:
  - "./"

overrides:
  "entities@4.5.0": "6.0.1"
  "websocket-driver": ">=0.7.5"

allowBuilds:
  bufferutil: set this to true or false
  core-js: set this to true or false
